# Generated by Django 6.1.2 on 2026-10-08 02:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Emoji opcional, ej: 🥃', max_length=8)),
            ],
            options={
                'verbose_name': 'tipo de licor',
                'verbose_name_plural': 'tipos de licor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Licor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=120)),
                ('grado_alcoholico', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='grado alcohólico (% vol)')),
                ('ph_minimo', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH mínimo')),
                ('ph_maximo', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH máximo')),
                ('ph_promedio', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH promedio')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='licores/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licores', to='licores.tipolicor')),
            ],
            options={
                'verbose_name': 'licor',
                'verbose_name_plural': 'licores',
                'ordering': ['tipo__nombre', 'nombre'],
            },
        ),
    ]
