# Generated by Django 6.1.2 on 2026-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licor',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL pública de una imagen (https://...). Se usa si no hay imagen subida.', max_length=500, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='licor',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen subida. Si se define, tiene prioridad sobre la URL.', null=True, upload_to='licores/'),
        ),
    ]
